apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: bestbuy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: vijayxavierwalter/bestbuy-order-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: "mongodb://mongodb:27017"
            - name: MONGO_DB_NAME
              value: "bestbuy"
            - name: MONGO_COLLECTION_NAME
              value: "orders"