apiVersion: v1
kind: Service
metadata:
  name: store-admin
  namespace: bestbuy
spec:
  selector:
    app: store-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer